/* Plain-English audit content. Static config (screenshots, references) lives in app.js. */
window.AUDIT = {
  homepage: {
    id: "homepage",
    lede: "This page covers the homepage — the first thing every visitor sees. The biggest problems are at the very top: a slow, blank opening, a headline that search engines can't read, and a search tool that doesn't work the way buyers expect.",
    shotcap: "The Silver Oak homepage — the video banner, the search bar, and the sections below.",
    findings: [
      { id:"A1", sev:"crit", title:"Blank grey screen at the top", problem:"For about 6 seconds after the page opens, the top of the homepage is a full-screen blank grey block while the video loads. It's the very first thing every visitor sees.", fix:"Show a still picture instantly while the video loads in the background." },
      { id:"A2", sev:"crit", title:"Headline is part of the video", problem:"The main headline, \"Invest in Dubai Real Estate With Experts\", is built into the video file. So it looks blurry, can't be highlighted, and is invisible to Google and to screen readers used by people with low vision. It also can't be changed without remaking the whole video.", fix:"Put the headline and subheading on the page as real text on top of the video." },
      { id:"A3", sev:"crit", title:"No clear action on the opening screen", problem:"The search bar — the main thing you want visitors to use — sits below the opening view. So when the page first loads there's nothing telling visitors what to do next.", fix:"Move the search bar up into the opening view and add a clear button like \"Talk to an Advisor\"." },
      { id:"A4", sev:"high", title:"Banner video is too large", problem:"The banner uses a heavy 7.3 MB video that loads slowly, has no still picture to cover the wait, and doesn't reliably start playing.", fix:"Use a smaller, lighter clip, add a still picture, and let it load only when needed." },
      { id:"A5", sev:"high", title:"Top bar colour doesn't change properly", problem:"As you scroll down, the top menu bar is supposed to turn navy but doesn't switch correctly.", fix:"Fix the colour change so the top bar turns navy on scroll." },
      { id:"A6", sev:"high", title:"Top bar stuck white after going back", problem:"After returning to the homepage, the top menu bar turns white and never goes back to navy, so it looks broken.", fix:"Reset the top bar to navy correctly when visitors return to the homepage." },
      { id:"A7", sev:"med", title:"Banner headline uses an odd font", problem:"The main banner text uses a font that doesn't match anything else on the site, so it looks out of place.", fix:"Use the site's standard fonts and make it real text." },
      { id:"A8", sev:"med", title:"Banner smaller text uses an odd font", problem:"The smaller banner text also uses a font that doesn't match the rest of the site.", fix:"Use the site's standard fonts." },
      { id:"A9", sev:"med", title:"Logo name is too small to read", problem:"The \"Silver Oak Properties\" name in the logo is tiny and hard to read against the navy bar.", fix:"Make the logo text bigger and easier to read." },
      { id:"A10", sev:"med", title:"Language picker makes the page jump", problem:"The flag and language picker loads blank and then pops in, which makes the rest of the page shift around as it appears.", fix:"Hold its space so nothing jumps when it loads." },
      { id:"A11", sev:"low", title:"Nothing shown while page loads", problem:"There's no loading screen or holding image while the page loads, so it can look like nothing is happening.", fix:"Add a light loading screen while the page loads." },
      { id:"A12", sev:"low", title:"Heavy video for a small effect", problem:"A heavy background video is used where a much lighter option would look the same, slowing the page for no real benefit.", fix:"Use a still picture with gentle movement, or a much smaller clip." },
      { id:"B1", sev:"high", title:"Can't search by type and place together", problem:"When a visitor picks a location, their property-type choice is wiped out, so they can't search for, say, a villa in a specific area at the same time.", fix:"Let the filters work together instead of cancelling each other out." },
      { id:"B2", sev:"high", title:"Search always assumes off-plan", problem:"The search never asks whether the visitor wants to rent, buy, or buy off-plan. It always assumes off-plan, so people looking to rent or buy a resale home are stuck.", fix:"Add a rent / buy / off-plan choice as a main filter." },
      { id:"B5", sev:"med", title:"Price box pre-filled at 500,000", problem:"The Starting Price box already has 500,000 typed in, so anyone looking below that price has to delete it first.", fix:"Leave the price box empty by default." },
      { id:"B6", sev:"med", title:"Search button cut off at the edge", problem:"The gold SEARCH button runs slightly off the side of the page and gets partly cut off.", fix:"Keep the button fully inside the page edge." },
      { id:"B7", sev:"med", title:"Search filters are hard to see", problem:"The search filter controls are faint and easy to miss, so visitors may not realise they can narrow their search.", fix:"Make the filters bolder and easier to spot." },
      { id:"E2", sev:"high", title:"Partner developers have no listings", problem:"Most of the developers listed under \"Developers Partnered With Us\" have no properties to show, so clicking them leads nowhere useful.", fix:"Hide the empty developers or add their listings." },
      { id:"E3", sev:"high", title:"Featured properties slider shows nothing", problem:"The homepage \"Exclusive Properties\" slider sometimes loads completely empty, showing no listings at all. It fails on and off.", fix:"Fix where the slider pulls its listings from so it always loads." },
      { id:"E5", sev:"med", title:"\"In Dubai\" includes non-Dubai homes", problem:"The \"Exclusive Properties in Dubai\" section also shows projects in Sharjah and Umm Al Quwain, so the label is misleading.", fix:"Fix the heading or the listings so they actually match." },
      { id:"E6", sev:"low", title:"Developer logos have no names", problem:"The developer logos are labelled \"Developer 1\" through \"Developer 12\" instead of their real brand names, which hurts Google search and access for people with low vision.", fix:"Label each logo with the real developer brand name." },
      { id:"E7", sev:"low", title:"Logo strip uneven and repeats", problem:"The scrolling developer logo strip has logos in mismatched sizes and shows some twice — EMAAR and NAKHEEL each appear two times.", fix:"Match the logo sizes and remove the duplicates." },
      { id:"H2", sev:"high", title:"\"Read All\" goes to wrong page", problem:"Clicking \"Read All\" on a customer review opens a page to write your own review instead of showing the actual review the visitor wanted to read.", fix:"Link \"Read All\" to the full review text instead." },
      { id:"H3", sev:"high", title:"Blog cards show no titles", problem:"The blog cards show only pictures with no titles, so visitors can't tell what each article is about before clicking.", fix:"Show the article title on each blog card." },
      { id:"H7", sev:"med", title:"Reviews cut off mid-sentence", problem:"Customer review cards stop in the middle of a sentence with \"...\" and are different heights, which looks messy.", fix:"End reviews at a whole word and make the cards the same height." },
      { id:"H8", sev:"med", title:"Confusing review section labels", problem:"The section is headed \"Achievements\" but then has a \"Google Reviews\" subtitle underneath, which doesn't make sense together.", fix:"Make the heading and subtitle match each other." },
      { id:"H9", sev:"low", title:"Awards are too pale to see", problem:"The Recognition & Awards images are very pale and hard to see against the white background.", fix:"Add a background card or border behind the award images." },
      { id:"H10", sev:"low", title:"FAQ text huge, no sources", problem:"The FAQ text is very large and the answers don't say where the information comes from, so it looks less trustworthy.", fix:"Make the FAQ text smaller and add sources for the answers." },
      { id:"I6", sev:"low", title:"Service icons sit unevenly", problem:"The \"Our Services\" icons alternate up and down in a zig-zag, so they look misaligned.", fix:"Line the service icons up evenly." },
      { id:"I7", sev:"low", title:"Priority-list form looks off", problem:"The priority-list sign-up card has a doubled shadow and a large empty gap, making it look unpolished.", fix:"Use one clean shadow and balance the layout." },
      { id:"J6", sev:"med", title:"Buttons click in the wrong spots", problem:"The social icons and \"Our Services\" buttons respond to clicks in areas that don't line up with the visible button, which feels broken.", fix:"Make the clickable area match the visible button or icon." }
    ]
  },

  offplan: {
    id: "offplan",
    lede: "This page reviews your off-plan property listings — the photos, prices, and the tools visitors use to browse. We found some prices that are wrong by hundreds of thousands of dirhams, photos that look distorted, and missing tools that make it hard for visitors to narrow down what they want.",
    shotcap: "The off-plan listings page — property cards with photos, prices, and contact buttons.",
    findings: [
      { id:"B3", sev:"high", title:"Visitors can't sort listings", problem:"Visitors have no way to reorder listings — not even cheapest to most expensive. Competitor sites let people sort by price, newest, and size, so yours feels harder to use.", fix:"Add a sort menu so visitors can order listings by price, newest, and size." },
      { id:"B4", sev:"high", title:"Search filters are too limited", problem:"Visitors can't narrow listings by bedrooms, bathrooms, size, community, or project status. They have to scroll through everything to find what fits them.", fix:"Add a full set of filters for bedrooms, bathrooms, size, community, and status." },
      { id:"B8", sev:"low", title:"Too few listings to test filters", problem:"There aren't enough properties on the site to see whether the filters actually work well for visitors.", fix:"Add more properties so the filters have enough listings to work with (see E1)." },
      { id:"C1", sev:"high", title:"Listing photos look stretched", problem:"Property photos are stretched out of shape to fit their boxes, so homes look distorted and unprofessional.", fix:"Set photos to a fixed shape so they crop neatly instead of stretching." },
      { id:"C2", sev:"high", title:"Stretched photos on the homepage too", problem:"The same stretched, distorted photos also appear on your homepage, where they are the first thing visitors see.", fix:"Apply the same photo fix on the homepage and everywhere else." },
      { id:"C3", sev:"med", title:"Blurry, over-zoomed photos", problem:"The photos on listing cards are low quality and zoomed in too far, so they look blurry and poorly framed.", fix:"Replace them with sharper, properly framed photos." },
      { id:"C4", sev:"med", title:"Too many contact buttons on cards", problem:"Every listing shows Call, Email, and WhatsApp buttons before a visitor has even opened the property. It makes the page look cluttered and repetitive.", fix:"Move the contact buttons onto the individual property page." },
      { id:"D1", sev:"crit", title:"Diamondz price overstated by ~790k", problem:"The site shows Diamondz by Danube starting at AED 1,890,000, but it actually starts near AED 1,100,000 for a studio — about 790,000 too high. Buyers may skip it thinking it's out of reach.", fix:"Correct the listing to the true starting price of about AED 1,100,000." },
      { id:"D2", sev:"crit", title:"One by Binghatti price too low by ~590k", problem:"The site shows One by Binghatti at AED 1,111,111, but it actually starts near AED 1,699,999 — about 590,000 too low. Buyers will arrive expecting a much lower price.", fix:"Correct the listing to the true starting price of about AED 1,699,999." },
      { id:"D3", sev:"crit", title:"Parkwood price too low by ~300k", problem:"The site shows Parkwood by Emaar at AED 1,450,000, but it actually starts near AED 1,750,000 — about 300,000 too low. This sets the wrong expectation for buyers.", fix:"Correct the listing to the true starting price of about AED 1,750,000." },
      { id:"D4", sev:"med", title:"Several smaller price mismatches", problem:"A few other listings have smaller wrong prices: Bayz 102 and Azizi Milan 20 are too high, while Sobha Orbis and Riverside Crescent 320 are too low.", fix:"Check each of these prices against your own records and correct them." },
      { id:"D5", sev:"med", title:"Azizi Milan shown in wrong area", problem:"Azizi Milan 30, 20, and 9 are labelled as being in Al Furjan, but the development is actually in City of Arabia / Dubailand. Visitors searching the right area won't find it.", fix:"Correct the location to City of Arabia / Dubailand." },
      { id:"D6", sev:"high", title:"Source can show fake prices", problem:"The 'AED 500,000,000' listing for Palace Residences at Al Mamsha isn't live now, but it came from the homepage feed, which can't be trusted to keep impossible prices off the site.", fix:"Review where listing prices come from and add checks that block impossible numbers." },
      { id:"E1", sev:"crit", title:"Only 39 properties on the site", problem:"The site only has 39 off-plan projects. The Buy, For-Sale, and Rent pages are all empty and show 'no properties found', so most visitors leave with nothing to view.", fix:"Add your for-sale and rental listings to fill the empty pages." },
      { id:"E4", sev:"med", title:"Empty Sharjah and UAQ pages", problem:"The Sharjah and Umm Al Quwain pages just say 'expansion in progress' with no listings, which looks unfinished to visitors.", fix:"Hide these pages until they have listings, or add some properties to them." }
    ]
  },

  detail: {
    id: "detail",
    lede: "This is the page a buyer lands on when they click a single property. It shows the photos, the price, the key facts, the payment plan and the brochure download. A few small things make the price and facts look untidy, and two problems could cost you leads.",
    shotcap: "A single property's page — photo gallery, price, key facts and the brochure download form.",
    findings: [
      { id:"I1", sev:"med", title:"Price uses a different lettering style", problem:"The price numbers are shown in a different style of lettering than the rest of the page, so the price looks slightly out of place next to everything around it.", fix:"Show the price in the same style of lettering used everywhere else on the page." },
      { id:"H1", sev:"high", title:"Brochures are missing content", problem:"When a buyer downloads a property brochure, a lot of the information is missing. They get a thin, half-finished document instead of a proper sales brochure.", fix:"Fill in the brochures so they are complete." },
      { id:"H5", sev:"med", title:"The return figure is shown twice", problem:"The expected return is printed twice, one line under the other: first \"ROI: 7-10%\" and then \"ROI up to 7-10% in Returns\". It reads as a mistake.", fix:"Delete the repeated line and keep one." },
      { id:"H6", sev:"med", title:"Some small captions make no sense", problem:"The little notes printed under the property facts are either pointless or don't make sense, which makes the page look unpolished.", fix:"Reword the captions or remove the ones that add nothing." },
      { id:"D7", sev:"med", title:"Rupee (INR) price uses an out-of-date rate", problem:"Buyers can switch the price between dirhams, dollars and rupees. The dollar figure is correct, but the rupee figure uses an out-of-date rate of 1 AED = 23.33 INR when the real rate is about 25.8 INR. The rupee price shown is therefore roughly 10% too low, so Indian buyers see a cheaper figure than the true cost.", fix:"Update the rupee rate to the current value (about 25.8 INR per AED) — ideally pull a live rate so it stays accurate. The dollar conversion is fine as is." },
      { id:"G2", sev:"high", title:"Brochure form accepts bad details", problem:"The Download Brochure form is meant to catch wrong details but does not do it well, especially phone numbers. You can end up with leads you cannot actually call back.", fix:"Tighten the form so it properly checks phone numbers and the other details." }
    ]
  },

  mortgage: {
    id: "mortgage",
    lede: "This page looks at the mortgage calculator and the linked affordability and pre-approval tools. A few issues make the calculator hard to use and risk showing visitors misleading numbers.",
    shotcap: "The mortgage calculator and its interest-rate, price, and affordability fields.",
    findings: [
      { id:"F1", sev:"high", title:"Shows results before numbers are valid", problem:"The calculator gives a result even when the numbers entered are too low to be valid, so visitors can see misleading figures. The affordability tool nearby waits until the numbers make sense, so the two tools don't behave the same way.", fix:"Make the calculator wait for valid numbers before showing a result, just like the affordability tool does." },
      { id:"F2", sev:"high", title:"Interest rate only moves in 0.1 jumps", problem:"Using the buttons, the interest rate only changes in steps of 0.1, so common rates like 3.99% or 4.99% can't be entered. Visitors can't get an accurate estimate.", fix:"Allow smaller rate steps and let visitors type the exact rate." },
      { id:"F3", sev:"high", title:"Can't type the interest rate", problem:"There is no way to type the interest rate by hand, so visitors are stuck using the buttons and can't enter the rate they actually have.", fix:"Let visitors type the interest rate directly into the field." },
      { id:"F4", sev:"med", title:"Example income wouldn't qualify", problem:"The sample monthly income shown in the affordability tool is below AED 10,000, which is too low to actually qualify for a mortgage. It sets a misleading expectation.", fix:"Use a realistic example income that would actually qualify." },
      { id:"F5", sev:"med", title:"Country code picker is buggy", problem:"On the Get Pre-approval form, the country-code picker for the phone number doesn't work properly. This can block visitors from submitting a pre-approval request.", fix:"Fix the country-code picker on the pre-approval form." },
      { id:"F6", sev:"low", title:"Dead arrow on interest rate field", problem:"There is an arrow next to the interest-rate field that does nothing when clicked. It looks broken to visitors.", fix:"Remove the arrow or make it work." },
      { id:"F7", sev:"low", title:"Dead arrow on property price field", problem:"There is an arrow in the property-price field that does nothing when clicked. It looks broken to visitors.", fix:"Remove the arrow or make it work." }
    ]
  },

  mobile: {
    id: "mobile",
    lede: "This page looks at how the website behaves on a phone, where most of your visitors browse. Most problems here come down to things being too small to tap or read — plus one piece of good news.",
    shotcap: "The Silver Oak home page as it appears on a phone screen.",
    findings: [
      { id:"M1", sev:"high", title:"Buttons too small to tap", problem:"On a phone, 104 of the 117 buttons and links are too small to tap accurately, including the menu button, the menu rows and the country picker. Visitors will keep missing them.", fix:"Make every button and link big enough to tap comfortably on a phone." },
      { id:"M2", sev:"high", title:"Text too tiny to read", problem:"On phones some text shrinks until it is almost invisible, including the US dollar and Indian rupee prices on the property cards. People cannot read the prices they came to see.", fix:"Set a sensible minimum text size so everything stays readable on phones." },
      { id:"M3", sev:"high", title:"Main headline unreadable on phones", problem:"The wide desktop video shrinks to a thin strip on a phone, so the headline sitting inside it becomes tiny and blurry. Your main message is lost on most visitors.", fix:"Use a phone-friendly image and show the headline as real text that stays sharp at any size." },
      { id:"M4", sev:"med", title:"Slide-in menu logo and old icon", problem:"The slide-in phone menu shows the same too-small logo and still uses the old Twitter bird, which looks dated.", fix:"Make the logo bigger and replace the Twitter bird with the current X icon." },
      { id:"M5", sev:"low", title:"No sideways scrolling (good)", problem:"Good news: on a phone the page does not slide sideways and nothing spills off the edge of the screen.", fix:"No action needed." }
    ]
  },

  sitewide: {
    id: "sitewide",
    lede: "This part of the audit covers issues that affect the whole site: how secure it is, whether your forms and chat actually deliver leads, and how consistent the branding and navigation feel. Several items here are urgent — including leads quietly failing to reach your sales system.",
    shotcap: "",
    findings: [
      { id:"L1", sev:"crit", title:"Form's secret keys exposed to anyone", problem:"The private keys that run the website's contact forms are written right into the public page, where anyone can find them. An outsider could use them to flood your inbox with fake enquiries or use up your paid quota. We confirmed this with one safe test.", fix:"Replace the exposed keys, turn on spam protection, and route form submissions through your own server." },
      { id:"L2", sev:"crit", title:"Enquiries never reach your CRM", problem:"When someone fills in a form, their details only land in a Gmail inbox and never reach Leadrat, your sales system. We confirmed this with a test enquiry: it arrived in Gmail but never showed up in the CRM. Real leads are slipping through the cracks.", fix:"Route form submissions through your own server so they land in Leadrat." },
      { id:"L3", sev:"crit", title:"Outsiders could redirect your leads", problem:"The form lets the sender choose where the enquiry gets delivered. An outsider could redirect your incoming leads to their own inbox or use your form to send spam.", fix:"Lock the delivery address on your own server and ignore any address sent from the visitor's browser." },
      { id:"L4", sev:"high", title:"Standard safety settings are missing", problem:"The site is missing several basic safety settings that browsers use to protect visitors, such as stopping another site from secretly framing yours. Your secure connection is fine, but these everyday protections are switched off.", fix:"Add the standard browser safety settings to the site's setup." },
      { id:"L5", sev:"high", title:"Admin login open to the whole internet", problem:"The login page where staff manage website content can be reached by anyone, anywhere, with nothing extra guarding it. That makes it an easy target for break-in attempts.", fix:"Require a second login step, lock out repeated wrong attempts, and limit access to trusted networks." },
      { id:"L6", sev:"med", title:"Staff email addresses left in the code", problem:"Internal staff email addresses (marketing@, info@, leads@) are sitting in the public page where anyone can collect them. That makes your team an easy target for phishing and spam.", fix:"Keep internal email addresses out of the public website pages." },
      { id:"L7", sev:"med", title:"Site advertises what it's built on", problem:"The website openly broadcasts the software it runs on. That hands attackers a useful head start when looking for weaknesses.", fix:"Hide the technical details the site doesn't need to reveal." },
      { id:"L8", sev:"low", title:"Sample placeholder data left live", problem:"Fake sample values like email@example.com, john@gmail.com and a made-up phone number were never removed and are still showing on the live site. It looks unfinished to visitors.", fix:"Remove the leftover sample and placeholder data." },
      { id:"J1", sev:"crit", title:"Chatbot tells visitors it's down", problem:"The chat assistant greets visitors by telling them it is unavailable. Anyone hoping to chat is turned away the moment they arrive.", fix:"Get the chatbot working again." },
      { id:"J2", sev:"crit", title:"Chat enquiries never reach your CRM", problem:"The chatbot and forms reassure visitors with \"sent, we'll contact you soon\", but the enquiry only lands in a Gmail inbox and never reaches Leadrat. We confirmed this with a test. Leads are being lost.", fix:"Connect chat and form submissions to Leadrat properly." },
      { id:"G1", sev:"high", title:"Phone fields accept any junk", problem:"The phone boxes on every form accept anything at all, with no check that a real number was entered. You end up with leads you can't call back.", fix:"Add proper phone-number checking on every form." },
      { id:"G3", sev:"med", title:"Country-code picker feels clumsy", problem:"The country-code picker on the forms is basic and awkward to use, which makes entering an international number harder than it should be.", fix:"Replace it with a proper international phone field." },
      { id:"J3", sev:"med", title:"Chat widget covers page content", problem:"The chat bubble sits on top of the page and covers the \"Our Services\" label and the social icons in the footer, hiding things visitors are trying to see.", fix:"Move the chat widget or add spacing so it stops covering content." },
      { id:"J4", sev:"med", title:"Chatbot is named \"Hi there\"", problem:"The chatbot's name shows up literally as \"Hi there\" with no profile photo, which looks unfinished and impersonal to visitors.", fix:"Give the chatbot a real name and a profile photo." },
      { id:"J5", sev:"med", title:"Offers to turn off alerts you never agreed to", problem:"The chat menu offers to \"turn off notifications\" even though visitors were never asked whether they wanted them on. It's confusing and looks broken.", fix:"Ask visitors first before offering to turn notifications off." },
      { id:"J7", sev:"med", title:"Team photos cut off people's heads", problem:"Some team photos in the contact section are cropped so the person's head isn't fully visible. It looks careless next to the people you want clients to trust.", fix:"Re-crop the team photos so faces show in full." },
      { id:"J8", sev:"med", title:"Menu opens jammed against the edge", problem:"The \"Who We Are\" dropdown opens hard against the right edge of the screen and risks running off the side, so part of it can be cut off.", fix:"Open the menu aligned to the right so it always stays on screen." },
      { id:"J9", sev:"med", title:"Menu uses the vague label \"Categories\"", problem:"The Properties menu tucks Area Guides and Blogs under a heading called \"Categories\" instead of a clear name like Insights or Resources. Visitors won't know what's in there.", fix:"Rename and reorganise that part of the menu under a clearer heading." },
      { id:"J10", sev:"low", title:"Footer shows the old Twitter logo", problem:"The footer still shows the old Twitter bird instead of the current X logo, which makes the site look out of date.", fix:"Swap the bird for the current X logo." },
      { id:"K1", sev:"high", title:"Fake phone number in the footer", problem:"The footer's phone link is a placeholder, +1234567890, not a real number. Anyone who taps it to call you reaches nothing.", fix:"Put your real phone number in the footer." },
      { id:"K2", sev:"med", title:"Contact email doesn't match the site", problem:"The contact email ends in .ae (info@silveroakglobal.ae) on a .com website. The mismatch can make people wonder whether it's genuine.", fix:"Use a contact email that matches the website's address." },
      { id:"K3", sev:"med", title:"Three different web addresses in use", problem:"The brand mixes three different web addresses (.com, .ae and .in) across the site. It looks disjointed and can make visitors unsure which is the real Silver Oak.", fix:"Pick one main web address and use it everywhere." },
      { id:"I2", sev:"med", title:"Fonts change across the site", problem:"The lettering style changes from one part of the site to another with no consistent plan, so the site feels patched together rather than polished.", fix:"Choose one set of fonts and use it everywhere." },
      { id:"I3", sev:"med", title:"Uneven gaps between sections", problem:"The spacing between sections jumps around with no steady rhythm, which makes the page feel untidy as you scroll.", fix:"Use one consistent set of spacing sizes throughout." },
      { id:"I4", sev:"med", title:"Content jumps left and right", problem:"Some sections start near the edge of the screen and others much further in, so the content visibly shifts side to side as visitors scroll down.", fix:"Line every section up to the same width." },
      { id:"I5", sev:"high", title:"Menu bar scrolls out of reach", problem:"The top menu isn't pinned in place, so on these very long pages it scrolls away and there's no quick way to get back to it. Visitors get stranded mid-page.", fix:"Keep the menu bar fixed at the top as visitors scroll." },
      { id:"E8", sev:"high", title:"Pages can load up blank", problem:"The main content is hidden until the browser finishes loading, with nothing shown in the meantime. If loading is slow or the tab is in the background, visitors (and Google) see only an empty shell. This is what causes the occasional blank property page and the empty carousel.", fix:"Show the main content right away, or a real loading placeholder, instead of hiding it." },
      { id:"H4", sev:"med", title:"\"50+ specialists\" but really 37", problem:"The About page claims \"50+ specialists\", but the team is actually 37. An exaggerated claim like this can dent trust if anyone checks.", fix:"State the real number of specialists." }
    ]
  }
};
